// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package com.karson.api.grpc;

public final class GrpcService {
  private GrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReplyPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReplyPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022grpc_service.proto\"!\n\016RequestPayload\022\017" +
      "\n\007message\030\001 \001(\t\"\037\n\014ReplyPayload\022\017\n\007messa" +
      "ge\030\001 \001(\t2o\n\007Request\022+\n\007request\022\017.Request" +
      "Payload\032\r.ReplyPayload\"\000\0227\n\017requestBiStr" +
      "eam\022\017.RequestPayload\032\r.ReplyPayload\"\000(\0010" +
      "\001B\027\n\023com.karson.api.grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestPayload_descriptor,
        new String[] { "Message", });
    internal_static_ReplyPayload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ReplyPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReplyPayload_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
