// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package com.karson.api.grpc;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */
  int getExtendInfoCount();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */
  boolean containsExtendInfo(
      String key);
  /**
   * Use {@link #getExtendInfoMap()} instead.
   */
  @Deprecated
  java.util.Map<String, String>
  getExtendInfo();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */
  java.util.Map<String, String>
  getExtendInfoMap();
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */

  String getExtendInfoOrDefault(
      String key,
      String defaultValue);
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */

  String getExtendInfoOrThrow(
      String key);
}
