// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package com.karson.api.grpc;

/**
 * Protobuf type {@code Payload}
 */
public final class Payload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Payload)
    PayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Payload.newBuilder() to construct.
  private Payload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Payload() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Payload();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Payload(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              extendInfo_ = com.google.protobuf.MapField.newMapField(
                  ExtendInfoDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<String, String>
            extendInfo__ = input.readMessage(
                ExtendInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            extendInfo_.getMutableMap().put(
                extendInfo__.getKey(), extendInfo__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GrpcService.internal_static_Payload_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetExtendInfo();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GrpcService.internal_static_Payload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Payload.class, Builder.class);
  }

  public static final int EXTENDINFO_FIELD_NUMBER = 1;
  private static final class ExtendInfoDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, String> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, String>newDefaultInstance(
                GrpcService.internal_static_Payload_ExtendInfoEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      String, String> extendInfo_;
  private com.google.protobuf.MapField<String, String>
  internalGetExtendInfo() {
    if (extendInfo_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtendInfoDefaultEntryHolder.defaultEntry);
    }
    return extendInfo_;
  }

  public int getExtendInfoCount() {
    return internalGetExtendInfo().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */

  @Override
  public boolean containsExtendInfo(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetExtendInfo().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtendInfoMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<String, String> getExtendInfo() {
    return getExtendInfoMap();
  }
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */
  @Override

  public java.util.Map<String, String> getExtendInfoMap() {
    return internalGetExtendInfo().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */
  @Override

  public String getExtendInfoOrDefault(
      String key,
      String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetExtendInfo().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; extendInfo = 1;</code>
   */
  @Override

  public String getExtendInfoOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<String, String> map =
        internalGetExtendInfo().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetExtendInfo(),
        ExtendInfoDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<String, String> entry
         : internalGetExtendInfo().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, String>
      extendInfo__ = ExtendInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, extendInfo__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Payload)) {
      return super.equals(obj);
    }
    Payload other = (Payload) obj;

    if (!internalGetExtendInfo().equals(
        other.internalGetExtendInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetExtendInfo().getMap().isEmpty()) {
      hash = (37 * hash) + EXTENDINFO_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExtendInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Payload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Payload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Payload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Payload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Payload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Payload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Payload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Payload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Payload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Payload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Payload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Payload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Payload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Payload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Payload)
      PayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GrpcService.internal_static_Payload_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetExtendInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableExtendInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GrpcService.internal_static_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Payload.class, Builder.class);
    }

    // Construct using com.karson.api.grpc.Payload.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      internalGetMutableExtendInfo().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GrpcService.internal_static_Payload_descriptor;
    }

    @Override
    public Payload getDefaultInstanceForType() {
      return Payload.getDefaultInstance();
    }

    @Override
    public Payload build() {
      Payload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Payload buildPartial() {
      Payload result = new Payload(this);
      int from_bitField0_ = bitField0_;
      result.extendInfo_ = internalGetExtendInfo();
      result.extendInfo_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Payload) {
        return mergeFrom((Payload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Payload other) {
      if (other == Payload.getDefaultInstance()) return this;
      internalGetMutableExtendInfo().mergeFrom(
          other.internalGetExtendInfo());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Payload parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Payload) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        String, String> extendInfo_;
    private com.google.protobuf.MapField<String, String>
    internalGetExtendInfo() {
      if (extendInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtendInfoDefaultEntryHolder.defaultEntry);
      }
      return extendInfo_;
    }
    private com.google.protobuf.MapField<String, String>
    internalGetMutableExtendInfo() {
      onChanged();;
      if (extendInfo_ == null) {
        extendInfo_ = com.google.protobuf.MapField.newMapField(
            ExtendInfoDefaultEntryHolder.defaultEntry);
      }
      if (!extendInfo_.isMutable()) {
        extendInfo_ = extendInfo_.copy();
      }
      return extendInfo_;
    }

    public int getExtendInfoCount() {
      return internalGetExtendInfo().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extendInfo = 1;</code>
     */

    @Override
    public boolean containsExtendInfo(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetExtendInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtendInfoMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, String> getExtendInfo() {
      return getExtendInfoMap();
    }
    /**
     * <code>map&lt;string, string&gt; extendInfo = 1;</code>
     */
    @Override

    public java.util.Map<String, String> getExtendInfoMap() {
      return internalGetExtendInfo().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extendInfo = 1;</code>
     */
    @Override

    public String getExtendInfoOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetExtendInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extendInfo = 1;</code>
     */
    @Override

    public String getExtendInfoOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, String> map =
          internalGetExtendInfo().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearExtendInfo() {
      internalGetMutableExtendInfo().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; extendInfo = 1;</code>
     */

    public Builder removeExtendInfo(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableExtendInfo().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, String>
    getMutableExtendInfo() {
      return internalGetMutableExtendInfo().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; extendInfo = 1;</code>
     */
    public Builder putExtendInfo(
        String key,
        String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableExtendInfo().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; extendInfo = 1;</code>
     */

    public Builder putAllExtendInfo(
        java.util.Map<String, String> values) {
      internalGetMutableExtendInfo().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Payload)
  }

  // @@protoc_insertion_point(class_scope:Payload)
  private static final Payload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Payload();
  }

  public static Payload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Payload>
      PARSER = new com.google.protobuf.AbstractParser<Payload>() {
    @Override
    public Payload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Payload(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Payload> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Payload> getParserForType() {
    return PARSER;
  }

  @Override
  public Payload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

