// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_service.proto

package com.karson.api.grpc;

public interface ReplyPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReplyPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
